version: "3"
######### Services ###################################
services:
  nginx:
    build:
      context: NGINX
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./NGINX/logs:/var/log/nginx
    ports:
      # Nuxt port
      - 8080:80
      # Laravel port
      - 8081:81
    networks:
      - back-end
      - front-end
    depends_on:
      - php
      - nodejs

  php:
    build:
      context: BACKEND/Docker/php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./BACKEND:/var/www/api
    environment:
      # If you down want to use xDebug, set remote_enable=0
      XDEBUG_CONFIG: "remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - back-end
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: homestead
      MYSQL_ROOT_PASSWORD: homestead
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - back-end

  redis:
    build:
      context: BACKEND/Docker/redis
      dockerfile: Dockerfile
    volumes:
      - ./BACKEND/Docker/redis:/data
    ports:
      - 63791:6379
    networks:
      - front-end
      - back-end

  nodejs:
    build:
      context: FRONTEND
      dockerfile: Dockerfile
    volumes:
      - ./FRONTEND:/var/www/client
    networks:
      - front-end

networks:
  front-end:
  back-end: