version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "5002:80"
    volumes:
      - ./BACKEND:/var/www/html
      - ./NGINX/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./BACKEND/Docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: homestead
      MYSQL_ROOT_PASSWORD: homestead
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  redis:
    image: redis:6.0.8
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./BACKEND/Docker/redis:/data
    depends_on:
      - php

  php:
    build:
      context: ./BACKEND/Docker/php
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./BACKEND:/var/www/html
